---
title: "CollaborativeBookdown: an opinionated approach to building a collaborative bookdown book"
author:
- name: Add author name
  affiliation: Add affiliation
- name: Sean Davis
  affiliation: Center for Cancer Research, National Cancer Institute, National Institutes of Health, Bethesda, MD
  email: seandavi@gmail.com
package: CollaborativeBookdown
output:
  BiocStyle::html_document
abstract: |
  The `r CRANpkg("bookdown")` package can be used to build gitbook books from
  multiple R markdown documents. The process for doing so is well-documented for
  a single user with a directory of R markdown documents. When dependencies 
  for chapters are complex, there are multiple contributors, and there is interest
  in having independent chapters, a slightly more complicated workflow is necessary.
  This vignette serves as a guide for colloboratively edited bookdown-based material
  where *each chapter is encapsulated by an independent R package*.
vignette: |
  %\VignetteIndexEntry{BookdownUtils: an opinionated approach to building a collaborative bookdown book}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Overview

The `r CRANpkg("bookdown")` package can be used to build gitbook books from
multiple R markdown documents. The process for doing so is well-documented for
a single user with a directory of R markdown documents. 

A more complicated use case includes some additional requirements.

- The materials and R packages required to successfully run the materials
in the book should be installable, including dependencies.
- Book chapters will be authored by individual contributors and each should
be able to control when new content is merged into the book while still
being able to work independently on their own materials.
- Contributions from each user should themselves be versioned, coupled to a
particular version of the book, and potentially decoupled from the book to 
include or exclude content.
- Individual chapters and (and should) be incorporated into individual installable
R packages so that R dependencies, code, and extended documentation can be included.
- The bookdown "parent" repository will depend on the packages from individual 
contributors. Installing the "parent" repository will lead to versioned installations
of each "chapter" repository.

# High-level implementation

- Parent package
  - DESCRIPTION file
    - contains Depends for each chapter package
    - contains Remotes for each chapter package, ideally tied to individual tag, branch, or commit.

Each contributed chapter package will contain the vignette and supporting materials. The Parent
package contains the bookdown configuration files. The `.Rmd` files for each chapter package will
be copied into the top-level directory of the Parent package by scripts in this package. 



# Editor workflow

- Create fork of Parent package
- Do local testing.
- Pull request.
- ???? Can we use github actions to perform CI/CD?

# Authoring notes

## Style macros

_BiocStyle_ introduces the following macros for referring to _R_ packages:

* `r Biocpkg("IRanges")`, for _Bioconductor_ software, annotation and experiment data packages,
* `r CRANpkg("data.table")`, for _R_ packages available on CRAN,
* `r Githubpkg("rstudio/rmarkdown")`, for _R_ packages available on GitHub,
* `r Rpackage("MyPkg")`, for _R_ packages that are _not_ available on _Bioconductor_, CRAN or GitHub.

# Session info {.unnumbered}

```{r sessionInfo, echo=FALSE}
sessionInfo()
```
